CC=g++
CFLAGS=-c -Wall
LDFLAGS=
SOURCES=sDeque_main.cpp sDeque.h sDeque.cpp mysDeque_main.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=sDeque

all: $(SOURCES) $(EXECUTABLE)
    
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *.o sDeque